### ISSUE TITLE
Parabolic interpolation for searching minima 

### ISSUE THREAD

**Issue by araihC** [INM-6/wavescalephant#30]
The method used in [1] Figure 8, a parabolic interpolation  for searching minima is needed. I am working on it, a pull request will follow.
[1] Celotto, M.; De Luca, C.; Muratore, P.; Resta, F.; Allegra Mascaro, A.L.; Pavone, F.S.; De Bonis, G.; Paolucci, P.S. Analysis and Model of Cortical Slow Waves Acquired with Optical Techniques. Methods Protoc. 2020, 3, 14.

**Comment by rgutzen** [comment]
I remember we had a long discussion about this part of the method last October, with the result that we intentionally didn't include it in the pipeline for two reasons.
1) Estimating the uncertainty of detecting the transition time based on the processed (incl. freq. filtered) fluorescence signals yields that the error margin of determining the transition onset by the minima is as least as large as the sampling rate. Therefore, interpolating the transition onset times in between the measurement points doesn't promise to improve the actual detection precision.
2) This part of the algorithm was computationally very expensive and because of 1) wasn't a necessary requirement of the method.

However, this could still be of interest for the purpose of replicating the original study you cite as closely as possible.

**Comment by rgutzen** [comment]
merged
