### ISSUE TITLE
Fitting amplitude distributions (stage03) is not robust

### ISSUE THREAD

**Issue by rgutzen** [INM-6/wavescalephant#37]
The current algorithm for fitting the amplitude distribution for separating UP and DOWN states tries to fit a Gaussian to the main peak. Then the other (UP) peak is separated by setting a threshold as a multiple of the standard deviation of the Gauss.
However, this implicitly assumes that the DOWN state is the dominant one, i.e. has a bigger peak. The algorithm completely fails if there are two equivalent peaks.

**Comment by rgutzen** [comment]
Alternative approach: Fit a double Gaussian and set central minimum as the UP/DOWN separation threshold

**Comment by gulpgiulia** [comment]
Double Gaussian was the very first approach (because it is what one expect, in theory, talking of bi-stability and bi-modality), but it caused more failures than success, especially when the level of anesthesia is low, since the up state values distribute more as a "hump" on the right profile of the down state gaussian peak rather than as a second gaussian peak. It seems clear that the more datasets we include, the more options we should insert in the fit block, keeping in mind that some settings may be dependent on datasets features (as e.g. anesthesia levels).
